### ISSUE TITLE
Watchdog  got triggered

### ISSUE THREAD

**Issue by vishnu-chalil** [alvarowolfx/asset-tracker-gcp-mongoose-os#2]
I really dont understand what is the problem but when I run after falshing the code I get this error
Somebody please Help

[Jul 20 13:22:28.841] Task watchdog got triggered. The following tasks did not reset the watchdog in time:
[Jul 20 13:22:28.849]  - IDLE (CPU 0), backtrace: 0x400d13f4 0x40085f77
[Jul 20 13:22:28.854] 
[Jul 20 13:22:28.854] Tasks currently running:
[Jul 20 13:22:28.856] CPU 0: mgos
[Jul 20 13:22:28.857] Aborting.
[Jul 20 13:22:28.858] abort() was called at PC 0x400d0f54 on core 0
[Jul 20 13:22:28.862] 
[Jul 20 13:22:28.862] Backtrace: 0x4008775f 0x4008785f 0x400d0f54 0x40081cba 0x40129d73
[Jul 20 13:22:28.868] --- BEGIN CORE DUMP ---
[Jul 20 13:22:28.869] mos: catching core dump

**Comment by vishnu-chalil** [comment]
And also can someone please tell what this means

[Jul 20 13:33:27.650] mgos_http_server_ini HTTP server started on [80]
[Jul 20 13:33:27.656] mgos_pppos_create    PPPoS UART1, 115200, fc off, APN 'www'
[Jul 20 13:33:27.664] mg_rpc_channel_uart  0x3ffd1000 UART0

**Comment by alvarowolfx** [comment]
Can you show your APN config and what cellular network provider are you using ?

**Comment by vishnu-chalil** [comment]
config_schema:
  - ["app", "o", {title: "App config"}]
  - ["app.update_interval", "i", 300, {title: "Update interval in seconds"}]
  - ["pppos.enable", true]
  - ["pppos.uart_no", 1]        
  - ["pppos.baud_rate", 115200]
  - ["pppos.apn", "airtelgprs.com"]
  - ["pppos.user", ""]
  - ["pppos.pass", ""]
  - ["pppos.connect_cmd", "ATD*99***1#"] 
  - ["gps.uart_no", 2]
  - ["gps.baud_rate", 9600]
  - ["gps.update_interval", 2000]
  - ["wifi.sta.enable", false]



Cellular network provider is airtel

**Comment by vishnu-chalil** [comment]
I found the mistake.It was an error with incorrect pin connection
