### ISSUE TITLE
MQTT SSL error

### ISSUE THREAD

**Issue by hexfusion** [alvarowolfx/asset-tracker-gcp-mongoose-os#4]
GCP is very sensitive to time sync issues which can result in MQTT SSL errors.

ref: https://github.com/mongoose-os-libs/gcp/issues/1

**Comment by vishnu-chalil** [comment]
I updated and build the firmware with new version tools and now I am stuck in this.All I get is this output

	[Aug  3 21:48:10.173] Setting timer with  300  seconds interval 
	[Aug  3 21:48:10.188]   at init.js:181
	[Aug  3 21:48:10.190] MJS error: calling non-callable
	[Aug  3 21:48:10.193] mgos_pppos_uart_disp Connecting (UART2, APN 'airtelgprs.com')...
	[Aug  3 21:48:10.201] mongoose_poll        New heap free LWM: 188456
	[Aug  3 21:48:10.206] mgos_net_on_change_c PPP: disconnected
	[Aug  3 21:48:12.690] mgos_net_on_change_c PPP: connecting
	[Aug  3 21:48:12.825] mgos_net_on_change_c PPP: connected
	[Aug  3 21:48:12.829] mgos_pppos_uart_disp Starting PPP, user ''
	[Aug  3 21:48:12.848] mongoose_poll        New heap free LWM: 186520
	[Aug  3 21:48:18.880] mgos_pppos_status_cb Error 6 (phase 0), reconnect
	[Aug  3 21:48:18.886] mgos_pppos_uart_disp Connecting (UART2, APN 'airtelgprs.com')...
	```
	[Aug  3 21:48:18.893] mgos_net_on_change_c PPP: disconnected
	[Aug  3 21:48:21.281] mgos_net_on_change_c PPP: connecting
	[Aug  3 21:48:21.796] mgos_net_on_change_c PPP: connected
	[Aug  3 21:48:21.801] mgos_pppos_uart_disp Starting PPP, user ''
	[Aug  3 21:48:21.820] mongoose_poll        New heap free LWM: 185688
	[Aug  3 21:48:27.851] mgos_pppos_status_cb Error 6 (phase 0), reconnect
	[Aug  3 21:48:27.857] mgos_pppos_uart_disp Connecting (UART2, APN 'airtelgprs.com')...


Is there something that I could have possibly missed
